# Generated by Django 4.1.2 on 2022-10-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(max_length=200)),
                ('allegries', models.CharField(max_length=150)),
                ('condition', models.CharField(max_length=200)),
                ('labresults', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.docs')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient')),
            ],
        ),
    ]
