# Generated by Django 4.1.2 on 2022-10-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.patient'),
        ),
    ]
