# Generated by Django 4.1.2 on 2022-10-17 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_records_allegries_alter_records_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='docs',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.docs'),
        ),
    ]
